[package]
name = "verify"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "1.0.1", default-features = false, features = ['std'] }
serde = "1.0"
bincode = "1.3"